services:
  - type: web
    name: bi-cloud-saas
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --workers 2 --threads 4 --timeout 180
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: EXCHANGE_API_KEY
        sync: false
