# Generated by Django 6.1 on 2026-09-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['order', 'id'], 'verbose_name': '검색 키워드', 'verbose_name_plural': '검색 키워드 목록'},
        ),
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(default=0, verbose_name='표시 순서'),
        ),
    ]
