# Generated by Django 6.1 on 2026-09-01 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_alter_keyword_options_keyword_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='날짜')),
                ('call_count', models.IntegerField(default=0, verbose_name='당일 호출 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API 사용량',
                'verbose_name_plural': 'API 사용량 기록',
            },
        ),
    ]
