# Generated by Django 6.1 on 2026-09-08 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_apiusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='검색 키워드')),
                ('title', models.CharField(max_length=500, verbose_name='기사 제목')),
                ('origin_url', models.URLField(db_index=True, max_length=1000, verbose_name='원문 링크')),
                ('press', models.CharField(blank=True, default='', max_length=100, verbose_name='언론사')),
                ('published_at', models.CharField(blank=True, default='', max_length=100, verbose_name='기사 발행일')),
                ('summary_points', models.JSONField(default=list, verbose_name='AI 핵심 요약 (3줄)')),
                ('business_implication', models.TextField(blank=True, default='', verbose_name='비즈니스 시사점')),
                ('raw_content', models.TextField(blank=True, default='', verbose_name='기사 원문 요약 스니펫')),
                ('memo', models.TextField(blank=True, default='', verbose_name='사용자 전략 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='아카이브 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='저장한 사용자')),
            ],
            options={
                'verbose_name': '저장된 기사',
                'verbose_name_plural': '저장된 기사 아카이브',
                'ordering': ['-created_at'],
            },
        ),
    ]
